# iOS CircleCI 2.1 configuration file
version: 2.1

orbs:
  tb-services: touchbistro/tb-services@volatile

################################################################################
#################################### JOBS ######################################
################################################################################
jobs:

  ############################## BUILD & TEST ##################################
  build_and_unit_test:
    executor: tb-services/macos-vm
    environment:
      FL_PLATFORM: ios
      FL_LANE: unit_test
    steps:
      - checkout
      - tb-services/v2-fastlane-test:
          build: true
      - tb-services/notify-slack-on-failure

  build_and_unit_test_mac:
    executor: tb-services/macos-vm
    environment:
      FL_PLATFORM: mac
      FL_LANE: unit_test
    steps:
      - checkout
      - tb-services/v2-fastlane-test:
          build: true
      - tb-services/notify-slack-on-failure


################################################################################
################################## WORKFLOWS ###################################
################################################################################
workflows:
  build-and-test:
    jobs:
      - build_and_unit_test:
          context: org-global
      - build_and_unit_test_mac:
          context: org-global